services:
  app-test:
    environment:
      - PYTEST_ADDOPTS=--cov=src --cov-branch --cov-report=xml:coverage/coverage.xml --cov-report=term-missing
      - COVERAGE_FILE=/usr/src/app/coverage/.coverage
    volumes:
      - ./coverage:/usr/src/app/coverage
