FROM python:3.13.13-bookworm

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=false
ENV PYTHONPATH=/usr/src/app

COPY ./poetry.lock ./pyproject.toml ./

RUN pip install --upgrade pip \
    && pip install poetry \
    && poetry install \
        --no-interaction \
        --no-ansi \
        --no-root

COPY ./src ./src
COPY ./tests ./tests
COPY ./alembic ./alembic
COPY ./scripts ./scripts

COPY \
    ./main.py \
    ./run_stream.py \
    ./alembic.ini \
    ./pytest.ini \
    ./
 