services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
      - DB_HOST=main_db
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - DocMind_network
    ports:
      - "8000:8000"
    depends_on:
      main_db:
        condition: service_healthy

  main_db:
    image: postgres:18.3-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-postgres}
    ports:
      - "5432:5432"
    networks:
      - DocMind_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_NAME:-postgres} -U ${DB_USER:-postgres}" ]
      interval: 5s
      timeout: 20s
      start_period: 10s
      retries: 10

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app
      - DB_HOST=main_db
    command: [ "poetry", "run", "alembic", "upgrade", "head" ]
    depends_on:
      main_db:
        condition: service_healthy
    networks:
      - DocMind_network

networks:
  DocMind_network:
    driver: bridge