"""add analysis_version field to documents table

Revision ID: 7da88587e149
Revises: c10c94257a0b
Create Date: 2026-06-13 16:21:35.706875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7da88587e149'
down_revision: Union[str, Sequence[str], None] = 'c10c94257a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('analysis_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'analysis_version')
    # ### end Alembic commands ###
