"""fix fields mime_type and document_status

Revision ID: c10c94257a0b
Revises: cdf1a08832ea
Create Date: 2026-05-19 13:24:25.845868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c10c94257a0b'
down_revision: Union[str, Sequence[str], None] = 'cdf1a08832ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'mime_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('txt', 'docx', 'xlsx', 'pdf', name='mime_type', native_enum=False),
               nullable=False)
    op.alter_column('documents', 'document_status',
               existing_type=postgresql.ENUM('created', 'queued', 'processing', 'success', 'failed', 'cancelled', name='document_status'),
               type_=sa.Enum('created', 'queued', 'processing', 'success', 'failed', 'cancelled', name='document_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_status',
               existing_type=sa.Enum('created', 'queued', 'processing', 'success', 'failed', 'cancelled', name='document_status', native_enum=False),
               type_=postgresql.ENUM('created', 'queued', 'processing', 'success', 'failed', 'cancelled', name='document_status'),
               existing_nullable=False)
    op.alter_column('documents', 'mime_type',
               existing_type=sa.Enum('txt', 'docx', 'xlsx', 'pdf', name='mime_type', native_enum=False),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
