"""update documents model to connect with Mongo

Revision ID: d195fc6dacf9
Revises: 7da88587e149
Create Date: 2026-06-18 12:53:33.887474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd195fc6dacf9'
down_revision: Union[str, Sequence[str], None] = '7da88587e149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'analysis_version')
    op.drop_column('documents', 'analysis')
    op.drop_column('documents', 'document_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('analysis', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('analysis_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
