"""add provider field to documents

Revision ID: e00a34658771
Revises: d195fc6dacf9
Create Date: 2026-06-23 20:34:23.711401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00a34658771'
down_revision: Union[str, Sequence[str], None] = 'd195fc6dacf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('provider', sa.Enum('gemini', 'deepseek', name='llm_provider', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'provider')
    # ### end Alembic commands ###
