"""remove provider field from document model

Revision ID: e25b01bf40a3
Revises: fb448f1c931b
Create Date: 2026-09-13 11:43:16.928000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25b01bf40a3'
down_revision: Union[str, Sequence[str], None] = 'fb448f1c931b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('provider', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
