"""add file_key field and update statuses

Revision ID: fb448f1c931b
Revises: 0a18a5ced57c
Create Date: 2026-07-27 21:25:13.436771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb448f1c931b'
down_revision: Union[str, Sequence[str], None] = '0a18a5ced57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_key')
    # ### end Alembic commands ###
